data <- read.table(file = "household_power_consumption.txt", sep = ";",
                   skip = 66637,nrows = 2880)
par(mfrow = c(2,2), cex=0.65)
days <- strptime(paste(data$V1, data$V2), format='%d/%m/%Y %H:%M:%S')
plot(days, data$V3, type="l", xlab="", ylab="Global Active Power")
plot(days, data$V5, type="l", xlab = "datetime", ylab="Voltage")
plot(days, data$V7, type="l", xlab="", ylab="Energy sub metering")
lines(days, as.numeric(as.character(data$V8)), type="l", col='Red')
lines(days, as.numeric(as.character(data$V9)), type="l", col='Blue')
plot(days, data$V4, type="l", xlab = "datetime", ylab = "Global_reactive_power")
dev.copy(png, 'plot4.png')
dev.off()